title: Alberto Niironen - ProgramaciÃ³n y FotografÃ­a
description: > # this means to ignore newlines until "baseurl:"
  Blog personal de Alberto Niironen, donde comparto mis experiencias en programaciÃ³n y fotografÃ­a.
  ArtÃ­culos, ideas, comentarios ... todo lo que se me ocurra.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://albertonii.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Alberto Niironen # add your name
author-img: alberto-niironen.jpg # add your photo
about-author: >
  Soy Alberto Niironen, un apasionado de la programaciÃ³n y la fotografÃ­a. En este blog comparto mis experiencias en ambos campos.
  Si te gusta la programaciÃ³n, la fotografÃ­a o simplemente quieres saber mÃ¡s sobre mi, este es tu sitio.
  Â¡Bienvenido!
location-author: Fuerteventura, Canary Islands ğŸï¸
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: albertonii # add your Github handle
social-linkedin: alberto-niironen-orduÃ±a-462855204 # add your Linkedin handle
social-email: alberto.niironen@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
